---
abstract: 'micro config loader'
author:
  - 'ytnobody, C<< <ytnobody aaaattttt gmail> >>'
build_requires:
  Test::More: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.2, CPAN::Meta::Converter version 2.130880'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Micro
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Config::Micro:
    file: lib/Config/Micro.pm
    version: 0.02
requires:
  File::Basename: 0
  File::Spec: 0
  perl: 5.01
resources:
  bugtracker: https://github.com/ytnobody/Config-Micro/issues
  homepage: https://github.com/ytnobody/Config-Micro
  repository: git://github.com/ytnobody/Config-Micro.git
version: 0.02
x_contributors:
  - 'ytnobody <ytnobody@gmail.com>'
